### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Dimentive** [BuiltBrokenModding/SBM-BaggableMobs#6]
Crash report: https://pastebin.com/raw/rAjc9Cdp

#### Versions

* **Minecraft:** 1.12.2 (duh)
* **Forge:** 14.23.5.2824 (latest)
* **Baggable Mobs:** 1.0.0 (duh)

**Comment by bl4ckscor3** [comment]
Already fixed in 7595cb9a0652b207084780993986d078a1930cd9

**Comment by Dimentive** [comment]
That’s good! 👍

When is the fixed version of the mod going to be released?

**Comment by DarkGuardsman** [comment]
hmm good question, thought it was already... check the alpha versions if not then I will need to poke @dmodoomsirius
